---
title: "bodycomp_size_PCanalysis"
author: "Abby Host"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

## Downloading NEW 2024(updated) Body Comp Data
```{r}
if(!require(tidyverse))install.packages("tidyverse");library(tidyverse)
if(!require(gsheet))install.packages("gsheet");library(gsheet)

bodycomp2019 <- read.csv("odata/NEWcrbody_2019.csv", header = TRUE)
bodycomp2020 <- read.csv("odata/NEWcrbody_2020.csv", header = TRUE)
bodycomp2021 <- read.csv("odata/NEWcrbody_2021.csv", header = TRUE)
```

## Organizing data for PC plots
```{r}
bodycomp2019 <- bodycomp2019[1:172,]
bodycomp2020 <- bodycomp2020[1:120,]
bodycomp2021 <- bodycomp2021[1:182,]
ALL_bodycomp <- rbind(bodycomp2019, bodycomp2020, bodycomp2021)
str(ALL_bodycomp)

#columns for PC analysis are all body size metrics so columns #10-18
pairs(ALL_bodycomp[,10:18], pch=".")



### CLEANING ALL BODY METRICS 
#cleaned_ALL_bodycomp <- na.omit(ALL_bodycomp[,c(1:18)]) #NEW data, no NAs-- all the body metrics cleaned up

## CLEANING BODY METRICS MINUS width and tape measurements, which has lots of NAs
cleaned_ALL_bodycomp <- na.omit(ALL_bodycomp[,c(1:10,11,13,15,18)])

mean(cleaned_ALL_bodycomp$Fish_Leng_2)
max(cleaned_ALL_bodycomp$Fish_Leng_2) #this might be incorrect, row = 57

cleaned_ALL_bodycomp <- cleaned_ALL_bodycomp[-(57),]#gets rid of row 57
cleaned_ALL_bodycomp <- cleaned_ALL_bodycomp[-(435),]
bc_pca1 <- princomp(cleaned_ALL_bodycomp[,c(10:14)], cor=T, scores=T, covmat = NULL) #should work now without any NAs
summary(bc_pca1, loadings=T, cutoff=0.0001) #summary of PC analysis

 #should work now without any NAs


unique(cleaned_ALL_bodycomp$Collection_Location)
cleaned_ALL_bodycomp$Collection_Location <- factor(cleaned_ALL_bodycomp$Collection_Location,
                       levels = c("Canyon Creek",
                                  "Fish Creek Gulkana",
                                  "Gulkana Hatchery",
                                  "Klutina River",
                                  "Mentasta",
                                  "Power Creek Cordova",
                                  "Eyak Weir Cordova",
                                  "St Anne",
                                  "Long Lake",
                                  "Mahlo",
                                  "Tanada",
                                  "Baird Canyon",
                                  "Chitina Airport",
                                  "Copper Lake",
                                  "Klutina Lake",
                                  "Upper Klutina",
                                  "Bone Creek"),
                       labels = c("CC",
                                  "FC",
                                  "GH",
                                  "KR",
                                  "MN",
                                  "PC",
                                  "EW",
                                  "SA",
                                  "LL",
                                  "MA",
                                  "TN",
                                  "BC",
                                  "CA",
                                  "CL",
                                  "KL",
                                  "KL",
                                  "BNC"))
#COLORS 
#CC = "#FFFFBF", FC = "#A6CEE3", GH = "#33A02C", Kr = "#F0027F", TN = "#CAB2D6", MN = "#FB9A99",  PC = "#FDC086", EW = "#666666", SA = "#FF7F00", LL= "#B2DF8A", MA = "#1F78B4", TN = "#5E4FA2", BC = "#FFED6F", CA = "#BDD3C7", CL = "darkblue", KL = "violet", BNC = "brown" 

install.packages("vegan")
library(vegan)

bc_pca1$scores
screeplot(bc_pca1, type=c('lines'))
cleaned_ALL_bodycomp$Collection_Location <- as.factor(cleaned_ALL_bodycomp$Collection_Location)
site_scores <- bc_pca1$scores[,1:4]
plot(site_scores[,1], site_scores[,2], col = cleaned_ALL_bodycomp$Collection_Location, pch=19, xlab= "PC-1", ylab = "PC-2")
legend("bottomleft", legend = unique(cleaned_ALL_bodycomp$Collection_Location), col=1:17, pch=19, cex=0.5)



# DONT USE
pca_vec <- envfit(bc_pca1$scores[,1:2], cleaned_ALL_bodycomp[,10:14], permutations=0)
plot(bc_pca1$scores[,1:2], cex = 1.5, asp = 1, pch=c(16), col=c("#FFFFBF", "#A6CEE3", "#33A02C", "#F0027F", "#CAB2D6", "#FB9A99", "#FDC086", "#666666", "#FF7F00", "#B2DF8A", "#1F78B4", "#5E4FA2","#FFED6F", "#BDD3C7", "darkblue", "brown"), ylab="", xlab="", cex.main=1.5, main = "PC 2 vs PC 1, with vectors indicating the correlation between the component scores")
legend(-6.5,2.5, legend = sort(unique(cleaned_ALL_bodycomp[,6])), col = c("#FFFFBF", "#A6CEE3", "#33A02C", "#F0027F", "#CAB2D6", "#FB9A99", "#FDC086", "#666666", "#FF7F00", "#B2DF8A", "#1F78B4", "#5E4FA2","#FFED6F", "#BDD3C7", "darkblue", "brown"), pch=c(16), cex=0.5, title ="Site")
plot(pca_vec, col="black", new = F, cex=1)
```
## WITHOUT EW, PC, CL and BNC
```{r}
#which vectors hold these locations?
new_ALL_bodycomp <- cleaned_ALL_bodycomp[-(454:455),] #no CL
new_ALL_bodycomp <- new_ALL_bodycomp[-(441:442),]
new_ALL_bodycomp <- new_ALL_bodycomp[-(91:131),]#no PC or EW


bc_pca2 <- princomp(new_ALL_bodycomp[,c(10:14)], cor=T, scores=T, covmat = NULL) #should work now without any NAs
summary(bc_pca2, loadings=T, cutoff=0.0001) #summary of PC analysis

bc_pca2$scores
screeplot(bc_pca2, type=c('lines'))
site_scores <- bc_pca2$scores[,1:5]
plot(site_scores[,1], site_scores[,2], col=c("#FFFFBF","#A6CEE3","#33A02C","#F0027F", "#CAB2D6", "#FB9A99", "#FF7F00","#B2DF8A","#1F78B4", "#5E4FA2","#FFED6F", "#BDD3C7","violet"), pch=19, xlab= "PC-1", ylab = "PC-2")
legend("bottomleft", legend = unique(new_ALL_bodycomp$Collection_Location), col=c("#FFFFBF","#A6CEE3","#33A02C","#F0027F", "#CAB2D6", "#FB9A99", "#FF7F00","#B2DF8A","#1F78B4", "#5E4FA2","#FFED6F", "#BDD3C7","violet"), pch=19, cex=0.5)


bc_pca2$scores
pca_vec <- envfit(bc_pca2$scores[,1:2], new_ALL_bodycomp[,10:14], permutations=0)
plot(bc_pca1$scores[,1:2], cex = 1.5, asp = 1, pch=c(16), col=c("#FFFFBF","#A6CEE3","#33A02C","#F0027F", "#CAB2D6", "#FB9A99", "#FF7F00","#B2DF8A","#1F78B4", "#5E4FA2","#FFED6F", "#BDD3C7","violet"), ylab="", xlab="", cex.main=1.5, main = "PC 2 vs PC 1, with vectors indicating the correlation between the component scores")
legend(-6.5,2.5, legend = sort(unique(new_ALL_bodycomp[,6])), col = c("#FFFFBF","#A6CEE3","#33A02C","#F0027F", "#CAB2D6", "#FB9A99", "#FF7F00","#B2DF8A","#1F78B4", "#5E4FA2","#FFED6F", "#BDD3C7","violet"), pch=c(16), cex=0.5, title ="Site")
plot(pca_vec, col="black", new = F, cex=1)
```


## PC Analysis (w/ all tape measurements, no weight)
```{r}
ALL_bodycomp <- rbind(bodycomp2019, bodycomp2020, bodycomp2021)
str(ALL_bodycomp)
ALL_bodycomp <- ALL_bodycomp[1:172,]


cleaned_ALL_bodycomp <- na.omit(ALL_bodycomp[,c(1:9,12,14,16,18)])#NEW data with no NAs in it

bc_pca1 <- princomp(cleaned_ALL_bodycomp[,c(10:13)], scale = T, cor=T, scores=T, covmat = NULL) #should work now without any NAs
summary(bc_pca1, loadings=T, cutoff=0.0001)

unique(cleaned_ALL_bodycomp$Collection_Location)
cleaned_ALL_bodycomp$Collection_Location <- factor(cleaned_ALL_bodycomp$Collection_Location,
                       levels = c("Canyon Creek",
                                  "Fish Creek Gulkana",
                                  "Gulkana Hatchery",
                                  "Klutina River",
                                  "Mentasta",
                                  "Power Creek Cordova",
                                  "Eyak Weir Cordova",
                                  "St Anne",
                                  "Long Lake",
                                  "Mahlo",
                                  "Tanada"),
                       labels = c("CC",
                                  "FC",
                                  "GH",
                                  "KR",
                                  "MN",
                                  "PC",
                                  "EW",
                                  "SA",
                                  "LL",
                                  "MA",
                                  "TN"))

bc_pca1$scores
screeplot(bc_pca1, type=c('lines'))
cleaned_ALL_bodycomp$Collection_Location <- as.factor(cleaned_ALL_bodycomp$Collection_Location)
site_scores <- cbind(cleaned_ALL_bodycomp$Collection_Location, bc_pca1$scores[,1:4])
plot(site_scores[,2], site_scores[,3], col = site_scores[,1], pch=19, xlab= "PC-1", ylab = "PC-2")
legend("bottomleft", legend = unique(site_scores[,1]), col=1:11, pch=19, cex=0.5)


pca_vec <- envfit(bc_pca1$scores[,1:2], cleaned_ALL_bodycomp[,10:13], permutations=0)
plot(bc_pca1$scores[,1:2], cex = 1.5, asp = 1, pch=c(16), col=c("#FFFFBF", "#A6CEE3", "#33A02C", "#F0027F", "#CAB2D6", "#FB9A99", "#FDC086", "#666666", "#FF7F00", "#B2DF8A", "#1F78B4", "#5E4FA2"), ylab="", xlab="", cex.main=1.5, main = "PC 2 vs PC 1, with vectors indicating the correlation between the component scores")
legend(-4.5,3, legend = sort(unique(cleaned_ALL_bodycomp[,6])), col = c("#FFFFBF", "#A6CEE3", "#33A02C", "#F0027F", "#CAB2D6", "#FB9A99", "#FDC086", "#666666", "#FF7F00", "#B2DF8A", "#1F78B4", "#5E4FA2"), pch=c(16), cex=0.75, title ="Site")
plot(pca_vec, col="black", new = F, cex=1)




#### what if I take out length_1
ALL_bodycomp <- rbind(bodycomp2019, bodycomp2020, bodycomp2021)
str(ALL_bodycomp)
ALL_bodycomp <- ALL_bodycomp[1:172,]


cleaned_ALL_bodycomp <- na.omit(ALL_bodycomp[,c(1:9,14,16,18)])#NEW data with no NAs in it

bc_pca1 <- princomp(cleaned_ALL_bodycomp[,c(10:12)], scale = T, cor=T, scores=T, covmat = NULL) #should work now without any NAs
summary(bc_pca1, loadings=T, cutoff=0.0001)

unique(cleaned_ALL_bodycomp$Collection_Location)
cleaned_ALL_bodycomp$Collection_Location <- factor(cleaned_ALL_bodycomp$Collection_Location,
                       levels = c("Canyon Creek",
                                  "Fish Creek Gulkana",
                                  "Gulkana Hatchery",
                                  "Klutina River",
                                  "Mentasta",
                                  "Power Creek Cordova",
                                  "Eyak Weir Cordova",
                                  "St Anne",
                                  "Long Lake",
                                  "Mahlo",
                                  "Tanada"),
                       labels = c("CC",
                                  "FC",
                                  "GH",
                                  "KR",
                                  "MN",
                                  "PC",
                                  "EW",
                                  "SA",
                                  "LL",
                                  "MA",
                                  "TN"))

bc_pca1$scores
screeplot(bc_pca1, type=c('lines'))
cleaned_ALL_bodycomp$Collection_Location <- as.factor(cleaned_ALL_bodycomp$Collection_Location)
site_scores <- cbind(cleaned_ALL_bodycomp$Collection_Location, bc_pca1$scores[,1:3])
plot(site_scores[,2], site_scores[,3], col = cleaned_ALL_bodycomp[,6], pch=19, xlab= "PC-1", ylab = "PC-2")
legend("bottomleft", legend = unique(cleaned_ALL_bodycomp[,6]), col=1:11, pch=19, cex=0.5)




pca_vec <- envfit(bc_pca1$scores[,1:2], cleaned_ALL_bodycomp[,10:12], permutations=0)
plot(bc_pca1$scores[,1:2], cex = 1.5, asp = 1, pch=c(16), col=c("#FFFFBF", "#A6CEE3", "#33A02C", "#F0027F", "#CAB2D6", "#FB9A99", "#FDC086", "#666666", "#FF7F00", "#B2DF8A", "#1F78B4", "#5E4FA2"), ylab="", xlab="", cex.main=1.5, main = "PC 2 vs PC 1, with vectors indicating the correlation between the component scores")
legend(-4.5,3, legend = sort(unique(cleaned_ALL_bodycomp[,6])), col = c("#FFFFBF", "#A6CEE3", "#33A02C", "#F0027F", "#CAB2D6", "#FB9A99", "#FDC086", "#666666", "#FF7F00", "#B2DF8A", "#1F78B4", "#5E4FA2"), pch=c(16), cex=0.75, title ="Site")
plot(pca_vec, col="black", new = F, cex=1)


```

## Fineness Ratios
```{r}
# fineness = ratio of total length to maximum width... *can i use girth (diameter via tape)



```


## Individual Year Principal Component Scores