---
title: "cr_sockeye2020"
author: "Abby Host"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
if(!require(tidyverse))install.packages("tidyverse");library(tidyverse)
if(!require(gsheet))install.packages("gsheet");library(gsheet)

write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1MRHgx_XU8p2nui4binK5fWNEP-T1lKE0iAwjSACcuU8/edit#gid=1888166607",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/crbody_2020.csv") #downloads 2019 body comp data from google sheets, make sure shareable by link in google

bodycomp2020 <- read.csv("odata/crbody_2020.csv")
```

## donwloading packages & adjusted data files
```{r}
library(lme4)
library(Matrix)
library(MASS)
library(dplyr)

#making site a factor in bodycomp2020 dataframe
bodycomp2020$site <- as.factor(bodycomp2020$site)
str(bodycomp2020)
```

## Energy Density Analysis for CC & Upper River
```{r}
write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1MRHgx_XU8p2nui4binK5fWNEP-T1lKE0iAwjSACcuU8/edit#gid=736449373",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/lowerriverdata_2020.csv")

lowerriver <- read.csv("odata/lowerriverdata_2020.csv")
lowerriver$runtime <- factor(lowerriver$runtime,
                             levels = c("early",
                                        "middle",
                                        "late"),
                             labels = c("Early",
                                        "Mid",
                                        "Late")) #changing labels within dataframe

write.csv(lowerriver, "wdata/workinglowerriverbodycomp_2019.csv")
str(lowerriver)

runtimeEmodel <- lm(EnergyDensity_mJ.kg_1~runtime, data = lowerriver)
anova(runtimeEmodel)

ggplot(lowerriver, aes(runtime, y=EnergyDensity_mJ.kg_1, fill = runtime)) + xlab("Run Timing Group") + ylab("Energy Density (mJ/kg)") + ggtitle("Energy Density (mJ/kg) across run-timing group in Canyon Creek") + geom_boxplot() +  scale_fill_manual(values = c("#1F78B4", "#E31A1C", "#FDBF6F")) +  theme(axis.title=element_text(size=14, face="bold"), axis.text.x = element_text(size=12), axis.text.y=element_text(size=12), title = element_text(size=16, face="bold"), legend.text = element_text(size=12)) + geom_jitter()




upperriver <- bodycomp2020[61:120,]
upperriver <- upperriver[-(22:23),]
upperriver <- upperriver[-(20),]#All upper river data samples (subtracting NAs)

#sites from 2020: MN, FC, GH, MA, SA, CL (n=1), LL

upperriver$site <- factor(upperriver$site,
                             levels = c("MN",
                                        "GH",
                                        "FC",
                                        "SA",
                                        "MA",
                                        "LL",
                                        "CL"),
                             labels = c("MN",
                                        "GH",
                                        "FC",
                                        "SA",
                                        "MA",
                                        "LL",
                                        "CL"))
```