---
title: "AFS Data Analysis"
author: "Abby Host"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
if(!require(tidyverse))install.packages("tidyverse");library(tidyverse)
if(!require(gsheet))install.packages("gsheet");library(gsheet)

#2019
write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1PuZgbr8eBlCNh1ygfhuv2W_xsryhhezn/edit#gid=1548316807",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/crbody_2019.csv") #downloads 2019 body comp data from google sheets, make sure shareable by link in google

write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1zOiVbDwnPme8mJdAlvX1QJ30etYJGBwA/edit#gid=1261110748",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/crpathogens_2019.csv") 

write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1PuZgbr8eBlCNh1ygfhuv2W_xsryhhezn/edit#gid=1571451659",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/bodypath_2019.csv") 

bodycomp2019 <- read.csv("odata/crbody_2019.csv")

#2020
write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1MRHgx_XU8p2nui4binK5fWNEP-T1lKE0iAwjSACcuU8/edit#gid=1888166607",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/crbody_2020.csv") #downloads 2019 body comp data from google sheets, make sure shareable by link in google

bodycomp2020 <- read.csv("odata/crbody_2020.csv")
bodycomp2020$site <- as.factor(bodycomp2020$site)
str(bodycomp2020)

#2021
write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1MRHgx_XU8p2nui4binK5fWNEP-T1lKE0iAwjSACcuU8/edit#gid=1634652378",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/crbody_2021.csv") #downloads 2019 body comp data from google sheets, make sure shareable by link in google

bodycomp2021 <- read.csv("odata/crbody_2021.csv")
bodycomp2021$site <- as.factor(bodycomp2021$site)
str(bodycomp2021)


```
### Energy Density & Run-Timing Group
```{r}
#2019
write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1PuZgbr8eBlCNh1ygfhuv2W_xsryhhezn/edit#gid=1774874016",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/lowerriverdata_2019.csv")

lowerriver19 <- read.csv("odata/lowerriverdata_2019.csv")
lowerriver19$runtime <- factor(lowerriver19$runtime,
                             levels = c("Early",
                                        "Mid",
                                        "Late"),
                             labels = c("Early",
                                        "Mid",
                                        "Late"))

write.csv(lowerriver19, "wdata/workinglowerriverbodycomp_2019.csv")
str(lowerriver19)
runtimeEmodel19 <- lm(EnergyDensity_mJ.kg_1~runtime, data = lowerriver19)
anova(runtimeEmodel19)

ggplot(lowerriver19, aes(runtime, y=EnergyDensity_mJ.kg_1, fill = runtime)) + xlab("Run Timing Group") + ylab("Energy Density (mJ/kg)") + ggtitle("Energy Density (mJ/kg) across run-timing group in Canyon Creek in 2019") + geom_boxplot() +  scale_fill_manual(values = c("#1F78B4", "#E31A1C", "#FDBF6F")) +  theme(axis.title=element_text(size=14, face="bold"), axis.text.x = element_text(size=12), axis.text.y=element_text(size=12), title = element_text(size=16, face="bold"), legend.text = element_text(size=12)) + geom_jitter()


ggplot(lowerriver19, aes(runtime, y=EnergyDensity_mJ.kg_1, fill = Sex)) + xlab("Run Timing Group") + ylab("Energy Density (mJ/kg)") + ggtitle("Energy Density (mJ/kg) across run-timing group in Canyon Creek in 2019") + geom_boxplot() +  scale_fill_manual(values = c("#1F78B4", "#E31A1C")) +  theme(axis.title=element_text(size=14, face="bold"), axis.text.x = element_text(size=12), axis.text.y=element_text(size=12), title = element_text(size=16, face="bold"), legend.text = element_text(size=12)) + geom_jitter() #trying to add a comparison of sex


#2020
write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1MRHgx_XU8p2nui4binK5fWNEP-T1lKE0iAwjSACcuU8/edit#gid=736449373",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/lowerriverdata_2020.csv")

lowerriver20 <- read.csv("odata/lowerriverdata_2020.csv")
lowerriver20$runtime <- factor(lowerriver20$runtime,
                             levels = c("early",
                                        "middle",
                                        "late"),
                             labels = c("Early",
                                        "Mid",
                                        "Late")) #changing labels within dataframe

write.csv(lowerriver20, "wdata/workinglowerriverbodycomp_2020.csv")
str(lowerriver20)

runtimeEmodel20 <- lm(EnergyDensity_mJ.kg_1~runtime, data = lowerriver20)
anova(runtimeEmodel20)

ggplot(lowerriver20, aes(runtime, y=EnergyDensity_mJ.kg_1, fill = runtime)) + xlab("Run Timing Group") + ylab("Energy Density (mJ/kg)") + ggtitle("Energy Density (mJ/kg) across run-timing group in Baird Canyon in 2020") + geom_boxplot() +  scale_fill_manual(values = c("#1F78B4", "#E31A1C", "#FDBF6F")) +  theme(axis.title=element_text(size=14, face="bold"), axis.text.x = element_text(size=12), axis.text.y=element_text(size=12), title = element_text(size=16, face="bold"), legend.text = element_text(size=12)) + geom_jitter()


#2021
write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1MRHgx_XU8p2nui4binK5fWNEP-T1lKE0iAwjSACcuU8/edit#gid=271403162",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/lowerriverdata_2021.csv")

lowerriver21 <- read.csv("odata/lowerriverdata_2021.csv")
lowerriver21$runtime <- factor(lowerriver21$runtime,
                             levels = c("Early",
                                        "Middle",
                                        "Late"),
                             labels = c("Early",
                                        "Mid",
                                        "Late")) #changing labels within dataframe

write.csv(lowerriver21, "wdata/workinglowerriverbodycomp_2021.csv")
str(lowerriver21)

runtimeEmodel21 <- lm(EnergyDensity_mJ.kg_1~runtime, data = lowerriver21)
anova(runtimeEmodel21)

ggplot(lowerriver21, aes(runtime, y=EnergyDensity_mJ.kg_1, fill = runtime)) + xlab("Run Timing Group") + ylab("Energy Density (mJ/kg)") + ggtitle("Energy Density (mJ/kg) across run-timing group in Baird Canyon in 2021") + geom_boxplot() +  scale_fill_manual(values = c("#1F78B4", "#E31A1C", "#FDBF6F")) +  theme(axis.title=element_text(size=14, face="bold"), axis.text.x = element_text(size=12), axis.text.y=element_text(size=12), title = element_text(size=16, face="bold"), legend.text = element_text(size=12)) + geom_jitter()

ggplot(lowerriver21, aes(runtime, y=EnergyDensity_mJ.kg_1, fill = Sex)) + xlab("Run Timing Group") + ylab("Energy Density (mJ/kg)") + ggtitle("Energy Density (mJ/kg) across run-timing group in Baird Canyon in 2021") + geom_boxplot() +  scale_fill_manual(values = c("#1F78B4", "#E31A1C")) +  theme(axis.title=element_text(size=14, face="bold"), axis.text.x = element_text(size=12), axis.text.y=element_text(size=12), title = element_text(size=16, face="bold"), legend.text = element_text(size=12)) + geom_jitter() #comparison of sex


#plots for poster-- Energy and Lower River run-timing
install.packages("gridExtra")
library(gridExtra)

low19 <- ggplot(lowerriver19, aes(runtime, y=EnergyDensity_mJ.kg_1, fill = runtime)) + xlab("Run Timing Group") + ylab("Energy Density (mJ/kg)") + ggtitle("2019") + geom_boxplot() +  scale_fill_manual(values = c("#1F78B4", "#E31A1C", "#FDBF6F")) + ylim(20,30) + theme(axis.title=element_text(size=20, face="bold"), axis.text.x = element_text(size=20), axis.text.y=element_text(size=20), title = element_text(size=24, face="bold"), legend.position = "none") + geom_jitter()
 
low20 <- ggplot(lowerriver20, aes(runtime, y=EnergyDensity_mJ.kg_1, fill = runtime)) + xlab("Run Timing Group") + ylab("Energy Density (mJ/kg)") + ggtitle("2020") + geom_boxplot() +  scale_fill_manual(values = c("#1F78B4", "#E31A1C", "#FDBF6F")) +  ylim(20,30) + theme(axis.title=element_text(size=20, face="bold"), axis.text.x = element_text(size=20), axis.title.y=element_blank(),  axis.text.y=element_text(size=20), title = element_text(size=24, face="bold"), legend.position = "none") + geom_jitter()
  
low21 <- ggplot(lowerriver21, aes(runtime, y=EnergyDensity_mJ.kg_1, fill = runtime)) + xlab("Run Timing Group") + ylab("Energy Density (mJ/kg)") + ggtitle("2021") + geom_boxplot() +  scale_fill_manual(values = c("#1F78B4", "#E31A1C", "#FDBF6F")) + ylim(20,30) + theme(axis.title=element_text(size=20, face="bold"), axis.text.x = element_text(size=20), axis.title.y=element_blank(),  axis.text.y=element_text(size=20), title = element_text(size=24, face="bold"), legend.position = "none") + geom_jitter()

grid.arrange(low19, low20, low21, ncol = 3)
```

### Energy Density & Spawning Site (Upper River)
```{r}
#2019
upperriver19 <- bodycomp2019[61:172,]
upperriver19 <- upperriver19[-(32:72),]
upperriver19 <- upperriver19[-(21),]#All upper river data samples (subtracting Eyak, Power Creek, and KL)

upperriver19$site <- factor(upperriver19$site,
                             levels = c("MN",
                                        "TN",
                                        "GH",
                                        "SA",
                                        "MA",
                                        "LL"),
                             labels = c("MN",
                                        "TN",
                                        "GH",
                                        "SA",
                                        "MA",
                                        "LL"))

write.csv(upperriver19, "wdata/upperriverbodycomp_2019.csv")
str(upperriver19)
upperriverEmodel19 <- lm(EnergyDensity_mJ.kg_1~site, data = upperriver19)
anova(upperriverEmodel19)

ggplot(upperriver19, aes(site, y=EnergyDensity_mJ.kg_1, fill = site)) + xlab("Sampling Site") + ylab("Energy Density (mJ/kg)") + ggtitle("Energy Density (mJ/kg) across 6 spawning sites in the Copper River, AK in 2019") + geom_boxplot() +  scale_fill_manual(values = c("#FB9A99", "#CAB2D6", "#33A02C","#FF7F00", "#E31A1C","#B2DF8A")) + theme(axis.title=element_text(size=18, face="bold"), axis.text.x = element_text(size=16), axis.text.y=element_text(size=12), title = element_text(size=20, face="bold"), legend.text = element_text(size=12)) + geom_jitter()

# title: Energy Density (mJ/kg) across 6 spawning sites in the Copper River, AK in the Copper River, AK in 2019.

#2020
upperriver20 <- bodycomp2020[61:120,]
upperriver20 <- upperriver20[-(22:23),]
upperriver20 <- upperriver20[-(20),]
upperriver20 <- upperriver20[-(47),] 
#All upper river data samples (subtracting NAs and the sole CL site)

#sites from 2020: MN, FC, GH, MA, SA, LL

upperriver20$site <- factor(upperriver20$site,
                             levels = c("MN",
                                        "FC",
                                        "GH",
                                        "SA",
                                        "MA",
                                        "LL"),
                             labels = c("MN",
                                        "FC",
                                        "GH",
                                        "SA",
                                        "MA",
                                        "LL"))

write.csv(upperriver20, "wdata/upperriverbodycomp_2020.csv")
str(upperriver20)
upperriverEmodel20 <- lm(EnergyDensity_mJ.kg_1~site, data = upperriver20)
anova(upperriverEmodel20)

ggplot(upperriver20, aes(site, y=EnergyDensity_mJ.kg_1, fill = site)) + xlab("Sampling Site") + ylab("Energy Density (mJ/kg)") + ggtitle("Energy Density (mJ/kg) across 6 spawning sites in the Copper River, AK in 2020") + geom_boxplot() +  scale_fill_manual(values = c("#FB9A99", "#9E0142","#33A02C", "#FF7F00", "#E31A1C","#B2DF8A")) + theme(axis.title=element_text(size=14, face="bold"), axis.text.x = element_text(size=12), axis.text.y=element_text(size=12), title = element_text(size=16, face="bold"), legend.text = element_text(size=12)) + geom_jitter()


#2021
upperriver21 <- bodycomp2021[61:187,]
#sites from 2021: MN, TN, FC, GH, MA, SA, CL (n=2), LL, KL, UKL (upper KL)
upperriver21 <- upperriver21[-(8),] #eliminates UKL
upperriver21$site <- factor(upperriver21$site,
                             levels = c("MN",
                                        "TN",
                                        "FC",
                                        "GH",
                                        "SA",
                                        "MA",
                                        "BN",
                                        "LL",
                                        "CL",
                                        "KL"),
                             labels = c("MN",
                                        "TN",
                                        "FC",
                                        "GH",
                                        "SA",
                                        "MA",
                                        "BN",
                                        "LL",
                                        "CL",
                                        "KL"))


upperriver21 <- upperriver21[-(112:113),] #eliminates Bone Creek
upperriver21 <- upperriver21[-(123:124),] #eliminates Copper Lake



upperriver21$site <- factor(upperriver21$site,
                             levels = c("MN",
                                        "TN",
                                        "FC",
                                        "GH",
                                        "SA",
                                        "MA",
                                        "LL",
                                        "KL"),
                             labels = c("MN",
                                        "TN",
                                        "FC",
                                        "GH",
                                        "SA",
                                        "MA",
                                        "LL",
                                        "KL"))

write.csv(upperriver21, "wdata/upperriverbodycomp_2021.csv")
str(upperriver21)
upperriverEmodel21 <- lm(EnergyDensity_mJ.kg_1~site, data = upperriver21)
anova(upperriverEmodel21)

#ggplot(upperriver21, aes(site, y=EnergyDensity_mJ.kg_1, fill = site)) + xlab("Sampling Site") + ylab("Energy Density (mJ/kg)") + ggtitle("Energy Density (mJ/kg) across 6 spawning sites in the Copper River, AK") + geom_boxplot() +  scale_fill_manual(values = c("#1F78B4", "#CAB2D6", "#FB9A99", "#33A02C","#FF7F00", "#E31A1C","#B2DF8A")) + theme(axis.title=element_text(size=14, face="bold"), axis.text.x = element_text(size=12), axis.text.y=element_text(size=12), title = element_text(size=16, face="bold"), legend.text = element_text(size=12)) + geom_jitter() 

#not enough colors, but keeping for consistency


ggplot(upperriver21, aes(site, y=EnergyDensity_mJ.kg_1, fill = site)) + xlab("Sampling Site") + ylab("Energy Density (mJ/kg)") + ggtitle("Energy Density (mJ/kg) across spawning sites in the Copper River, AK in 2021") + geom_boxplot() +  scale_fill_manual(values = c("#FB9A99", "#CAB2D6", "#33A02C","#9E0142", "#FF7F00", "#E31A1C", "#B2DF8A","#66C2A5")) + theme(axis.title=element_text(size=14, face="bold"), axis.text.x = element_text(size=12), axis.text.y=element_text(size=12), title = element_text(size=16, face="bold"), legend.text = element_text(size=12)) + geom_jitter()



# code for colors: TN = "#CAB2D6", MN = "#FB9A99", GH = "#33A02C", SA = "#FF7F00", MA = "#E31A1C", LL= ""#B2DF8A", FC = "#9E0142", BN = ""#FDAE61", CL = "#FFFFBF", KL = ""#66C2A5"


#plots for poster-- Energy and Lower River run-timing
install.packages("gridExtra")
library(gridExtra)

upper19 <- ggplot(upperriver19, aes(site, y=EnergyDensity_mJ.kg_1, fill = site)) + xlab("Sampling Site") + ylab("Energy Density (mJ/kg)") + ggtitle("2019") + geom_boxplot() +  scale_fill_manual(values = c( "#FB9A99", "#CAB2D6","#33A02C","#FF7F00", "#E31A1C","#B2DF8A")) + ylim(15,26)+ theme(axis.title=element_text(size=20, face="bold"), axis.text.x = element_text(size=20), axis.text.y=element_text(size=20), title = element_text(size=24, face="bold"), legend.position = "none") + geom_jitter()
 
upper20 <- ggplot(upperriver20, aes(site, y=EnergyDensity_mJ.kg_1, fill = site)) + xlab("Sampling Site") + ylab("Energy Density (mJ/kg)") + ggtitle("2020") + geom_boxplot() +  scale_fill_manual(values = c("#FB9A99","#9E0142","#33A02C", "#FF7F00", "#E31A1C","#B2DF8A")) + ylim(15,26) + theme(axis.title=element_text(size=20, face="bold"), axis.text.x = element_text(size=20), axis.text.y=element_text(size=20), axis.title.y=element_blank(), title = element_text(size=24, face="bold"), legend.position = "none") + geom_jitter()
  
upper21 <- ggplot(upperriver21, aes(site, y=EnergyDensity_mJ.kg_1, fill = site)) + xlab("Sampling Site") + ylab("Energy Density (mJ/kg)") + ggtitle("2021") + geom_boxplot() +  scale_fill_manual(values = c("#FB9A99", "#CAB2D6","#9E0142", "#33A02C", "#FF7F00", "#E31A1C", "#B2DF8A","#66C2A5")) +ylim(15,26) + theme(axis.title=element_text(size=20, face="bold"), axis.text.x = element_text(size=16), axis.text.y=element_text(size=20), axis.title.y=element_blank(), title = element_text(size=24, face="bold"), legend.text = element_text(size=20)) + geom_jitter()


grid.arrange(upper19, upper20, upper21, ncol = 3)

```
### Body Composition for 2019
```{r}
# fecundity vs site? -- Crossin et al. "egg number (fecundity) and ovary mass decrease with migration distance (Linley, 1993), reflecting an energetic necessity to invest in other functions affecting reproductive success"

#in this dataset == fecundity weight is (Female fecundity estimate 1 - weight of eggs in subsample 1 (g))

#ANOVA/linear analysis for fecundity_wt and site
upperriverFecundity19 <- lm(Fem_Fecun_1_wt~site, data=upperriver19)
anova(upperriverFecundity19)

ggplot(data=subset(upperriver19, !is.na(Fem_Fecun_1_wt)), aes(site, y=Fem_Fecun_1_wt, fill = site)) + xlab("Sampling Site") + ylab("Female Fecundity Weight") + ggtitle("Female Fecundity across 6 spawning sites in the Copper River, AK in 2019") + geom_boxplot() +  scale_fill_manual(values = c("#FB9A99", "#CAB2D6", "#33A02C","#FF7F00", "#E31A1C","#B2DF8A")) + theme(axis.title=element_text(size=18, face="bold"), axis.text.x = element_text(size=16), axis.text.y=element_text(size=12), title = element_text(size=20, face="bold"), legend.text = element_text(size=12)) + geom_jitter()


#what about fecundity #?
upperriverFecunditynum19 <- lm(Fem_Fecun_1_num~site, data=upperriver19)
anova(upperriverFecunditynum19)

ggplot(data=subset(upperriver19, !is.na(Fem_Fecun_1_num)), aes(site, y=Fem_Fecun_1_num, fill = site)) + xlab("Sampling Site") + ylab("Female Fecundity Number (# Eggs)") + ggtitle("Female Fecundity across 6 spawning sites in the Copper River, AK in 2019") + geom_boxplot() +  scale_fill_manual(values = c("#FB9A99", "#CAB2D6", "#33A02C","#FF7F00", "#E31A1C","#B2DF8A")) + theme(axis.title=element_text(size=18, face="bold"), axis.text.x = element_text(size=16), axis.text.y=element_text(size=12), title = element_text(size=20, face="bold"), legend.text = element_text(size=12)) + geom_jitter()

#what about egg size?
upperrivereggsize19 <- lm(Fem_Egg_Sz_1~site, data=upperriver19)
anova(upperrivereggsize19)

ggplot(data=subset(upperriver19, !is.na(Fem_Egg_Sz_1)), aes(site, y=Fem_Egg_Sz_1, fill = site)) + xlab("Sampling Site") + ylab("Female Egg Size") + ggtitle("Female Egg Size across 6 spawning sites in the Copper River, AK in 2019") + geom_boxplot() +  scale_fill_manual(values = c("#FB9A99", "#CAB2D6", "#33A02C","#FF7F00", "#E31A1C","#B2DF8A")) + theme(axis.title=element_text(size=18, face="bold"), axis.text.x = element_text(size=16), axis.text.y=element_text(size=12), title = element_text(size=20, face="bold"), legend.text = element_text(size=12)) + geom_jitter()


#what about gonad mass? (overall, not divided by female/male)
upperrivergonadmass19 <- lm(Gonad_Wt~site, data=upperriver19)
anova(upperrivergonadmass19)

ggplot(data=subset(upperriver19, !is.na(Gonad_Wt)), aes(site, y=Gonad_Wt, fill = site)) + xlab("Sampling Site") + ylab("Gonad Weight (g)") + ggtitle("Gonad Weight across 6 spawning sites in the Copper River, AK in 2019") + geom_boxplot() +  scale_fill_manual(values = c("#FB9A99", "#CAB2D6", "#33A02C","#FF7F00", "#E31A1C","#B2DF8A")) + theme(axis.title=element_text(size=18, face="bold"), axis.text.x = element_text(size=16), axis.text.y=element_text(size=12), title = element_text(size=20, face="bold"), legend.text = element_text(size=12)) + geom_jitter()

#divided by male and female
ggplot(data=subset(upperriver19, !is.na(Gonad_Wt)), aes(x=site, y=Gonad_Wt, fill = Sex)) + xlab("Sampling Site") + ylab("Gonad Weight (g)") + ggtitle("Gonad Weight across 6 spawning sites in the Copper River, AK in 2019") + geom_boxplot() +  scale_fill_manual(values = c("#1F78B4", "#E31A1C")) + theme(axis.title=element_text(size=18, face="bold"), axis.text.x = element_text(size=16), axis.text.y=element_text(size=12), title = element_text(size=20, face="bold"), legend.text = element_text(size=12)) + geom_jitter()

```

### 2019 Energy and Somatic Indices-- Linear Analysis
```{r}
up19_ED_fecund_lm <- lm(upperriver19$EnergyDensity_mJ.kg_1 ~ upperriver19$Fem_Fecun_1_wt)
summary(up19_ED_fecund_lm)
anova(up19_ED_fecund_lm)
ggplot(upperriver19, aes(Fem_Fecun_1_wt, EnergyDensity_mJ.kg_1)) + geom_point() + geom_smooth(method = "lm", col = "blue") #negatively correlated but not significantly


#ovary weight vs energy
up19_ED_ovarymass_lm <- lm(EnergyDensity_mJ.kg_1 ~ Gonad_Wt, data=subset(upperriver19, Sex=="F"))
summary(up19_ED_ovarymass_lm)
anova(up19_ED_ovarymass_lm)
ggplot(data=subset(upperriver19,Sex=="F"), aes(Gonad_Wt, EnergyDensity_mJ.kg_1)) + geom_point() + geom_smooth(method = "lm", col = "blue")

#ovary weight and site vs energy
up19_ED_ovarysite_lm <- lm(EnergyDensity_mJ.kg_1 ~ Gonad_Wt + site, data=subset(upperriver19, Sex=="F"))
summary(up19_ED_ovarysite_lm)
anova(up19_ED_ovarysite_lm)






```




### 2019 Pathogens
```{r}
write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1PuZgbr8eBlCNh1ygfhuv2W_xsryhhezn/edit#gid=1571451659",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/bodypath_2019.csv") 

bodycomp <- read.csv("odata/crbody_2019.csv")
path <- read.csv("odata/crpathogens_2019.csv")
bodypath <- read.csv("odata/bodypath_2019.csv") #full dataset w/ body comp AND pathogen results for 2019

library(lme4)
library(Matrix)
library(MASS)
library(dplyr)

#making site a factor in bodypath dataframe
bodypath$site <- as.factor(bodypath$site)
str(bodypath)

bodypath
#subset bodypath to get rid of Eyak and Power Creek rows
bodypath1 <- bodypath[-(33:48),]
#bodypath1$pathprevalence <- (bodypath1$path_richness / 37)

# size-corrected body mass
# regression with body weight and body length (size corrected body mass AKA sc_bm)
bodypath1 <- bodypath1[-(57),] #eliminates TN1 b/c it lacks data
sc_bm_lm <- lm(bodypath1$Fish_Wt ~ bodypath1$Fish_Leng_1)
sc_bm_resid <- residuals(sc_bm_lm) 
sc_bm_resid
plot(sc_bm_resid, bodypath1$Fish_Leng_1)
length(bodypath1$Fish_Leng_1)

sc_bodymass <- as.data.frame(sc_bm_resid)
bodypath1 <- cbind(bodypath1, sc_bodymass) #adding residuals as a column for size corrected body mass
library(dplyr)
names(bodypath1)[names(bodypath1)== "sc_bm_resid"] <- "sc_bodymass" #rename column

bodypath1 <- bodypath1[-(45),] #eliminates LL6, which has a -999 value of ihnv, which i eliminated via NA in the path loadings

#may need to eliminate SA5 because no data for E content -- maybe not though?
write.csv(bodypath1, "wdata/bodypathogenanalysis_data2019.csv")

# energy density
bodypath1$EnergyDensity_mJ.kg_1

#total energy??
#how to calculate this? == E density * Fish Weight
bodypath1$totalE <- (bodypath1$EnergyDensity_mJ.kg_1*bodypath1$Fish_Wt)


pathrichness <- bodypath1[,c(1:2,6,49:86)]
write.csv(pathrichness, "wdata/2019_pathogenrichness.csv") # smaller data frame with pathogen richness, for presentation

# prevalence was calculated in excel spreadsheet for simplicity, not used for code

#bodypath1$path_richness 
## path richness column, all adjusted for columns that needed to be removed/rows that needed to be removed

write.csv(read.csv(text=gsheet2text("https://docs.google.com/spreadsheets/d/1zOiVbDwnPme8mJdAlvX1QJ30etYJGBwA/edit#gid=855164179",format="csv"),stringsAsFactors = F),
          row.names = FALSE,
          "odata/updatedpathogens_2019.csv") 

path <- read.csv("odata/updatedpathogens_2019.csv")
#path <- path[-c(9:16,57:64,73),] #eliminate PC and EW data, and TN1 which lacks body comp data in other datasheet
str(path)


path_loads <- subset(path, select = c(unique_id,site, fluidigm_num, 10:55))
str(path_loads)
path_work <- subset(path_loads, select = c(1:6, 8:9, 11:15, 17:18, 20:25, 27:30, 32:34, 36, 38, 40:49))
str(path_work)

#transforming data, testing w/ histograms
path_work <- path_work %>%
  mutate(c_b_cys = log(c_b_cys + 1))

path_work <- path_work %>%
  mutate(de_sal = log(de_sal + 1))

path_work <- path_work %>%
  mutate(fa_mar = log(fa_mar + 1))

path_work <- path_work %>%
  mutate(fl_psy = log(fl_psy + 1))

path_work <- path_work %>%
  mutate(ic_hof = log(ic_hof + 1))

path_work <- path_work %>%
  mutate(ic_mul = log(ic_mul + 1))

path_work <- path_work %>%
  mutate(ihnv = log(ihnv + 1))

path_work <- path_work %>%
  mutate(lo_sal = log(lo_sal + 1))

path_work <- path_work %>%
  mutate(pa_kab = log(pa_kab + 1))

path_work <- path_work %>%
  mutate(pa_min = log(pa_min + 1))

path_work <- path_work %>%
  mutate(pa_pse = log(pa_pse + 1))

path_work <- path_work %>%
  mutate(pa_ther = log(pa_ther + 1))

path_work <- path_work %>%
  mutate(sch = log(sch + 1))

path_work <- path_work %>%
  mutate(sp_des = log(sp_des + 1))

path_work <- path_work %>%
  mutate(te_bry = log(te_bry + 1))

str(path_work)


#remove pathogens with all 0 loads
path_work <- subset(path_work, select = c(1:3, 7, 11:17, 22:25, 31, 33:34))
path_work <- path_work[-c(9:16,57:64,73),] #eliminates EW and PC data rows, eliminates TN1 because it lacks bodycomp data for analysis in future

path_work <- path_work[,-(15:16)] #eliminates sch and path_ther, b/c no prevalence without EW and PC
pairs(path_work[,4:16])
write.csv(path_work, "wdata/workingpathogendata.csv") #saving this datafile, in case -- log transformations, only includes pathogens with loadings present for at least one fish in one CR location

#PCA
path_work <- drop_na(path_work) #dropping NA values from data (this drops LL6 ======= NEED TO ADDENDUM THIS IN BODYPATH1 for future analysis)
path_pca <- princomp(path_work[,4:16],cor=T, scores=T, covmat = NULL)
summary(path_pca, loadings=T, cutoff=0.000001) #use to interpret
library("knitr")
library(kableExtra)

#organize sites with colors
path_work$site <- factor(path_work$site,
                             levels = c("CC",
                                        "LL",
                                        "MA",
                                        "SA",
                                        "GH",
                                        "MN",
                                        "TN"),
                             labels = c("CC",
                                        "LL",
                                        "MA",
                                        "SA",
                                        "GH",
                                        "MN",
                                        "TN"))

#vegan() for analysis, plotting, and ordination of multivariate datasets.
install.packages("vegan")
library(vegan)
pca_vec <- envfit(path_pca$scores[,1:2], path_work[,4:16], permutations=0)
plot(path_pca$scores[,1:2], cex=1.5, asp=1, pch=c(16), col=c("#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FF7F00", "#CAB2D6"), ylab="", xlab="", cex.main=1.5, main = "PC 2 vs PC 1, with vectors indicating the correlation between the component scores")
mtext("Principal Component 2", side=2, line=2.2, cex=1.5)
mtext("Principal Component 1", side=1, line=2.2, cex=1.5)
legend(7,4.5, legend = sort(unique(path_work[,2])), col = c("#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C",  "#FF7F00", "#CAB2D6"), pch=c(16), cex=1.2, title ="Site")
plot(pca_vec, col="black", new = F, cex=1) #The envfit() function fits vectors indicating the correlation between the component scores (plotted in the scatterplot)


## For Principal component analysis, interpretation is based on finding which variables are most strongly correlated with each component, i.e., which of these numbers are large in magnitude, the farthest from zero in either direction. 
## Looking at loadings, the following pathogens are the largest in magnitude and therefore the most strongly correlated with Principle Component #1: fl_psy > hkg > c_b_cys > ihnv > ic_mul
#for principle component #2: pa_min > pa_pse > te_bry > de_sal > sch

#why the PCA? --  simplifies the complexity in high-dimensional data while retaining trends and patterns

path_pca
path_pca$scores

screeplot(path_pca, type=c('lines'), main = "Line Screeplot for Pathogen PCA")

path_work$site <- as.factor(path_work$site)
site_scores<-cbind(path_work$site, path_pca$scores[,1:4])
site_scores <- as.data.frame(site_scores)
str(site_scores)
site_scores$V1 <- as.factor(site_scores$V1)
site_scores$Comp.1 <- as.numeric(site_scores$Comp.1)
site_scores$Comp.2 <- as.numeric(site_scores$Comp.2)
site_scores$Comp.3 <- as.numeric(site_scores$Comp.3)
site_scores$Comp.4 <- as.numeric(site_scores$Comp.4)

library(RColorBrewer)
display.brewer.all()
display.brewer.pal(n=9, name = "Paired")
brewer.pal(n = 9, name = "Paired")
brewer.pal(n = 11, name = "Spectral")
# "#A6CEE3"  "#B2DF8A" "#33A02C" "#FB9A99" "#E31A1C" "#FDBF6F" "#FF7F00" "#CAB2D6"



#PC2 vs PC1 figure
plot(site_scores[,2], site_scores[,3], col=c("#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FF7F00", "#CAB2D6"), pch=19, xlab= "PC-1", ylab = "PC-2", main="PC-2 vs PC-1")
legend("bottomleft", legend = unique(site_scores[,1]), col=c("#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FF7F00", "#CAB2D6"), pch=19, cex=0.5)


#PC3 vs PC1 figure
plot(site_scores[,2], site_scores[,4], col=c("#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FF7F00", "#CAB2D6"), pch=19, xlab= "PC-1", ylab = "PC-3", main="PC-3 vs PC-1")
legend("bottomleft", legend = unique(site_scores[,1]),col=c("#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FF7F00", "#CAB2D6"), pch=19, cex=0.5)

#PC3 vs PC2 figure
plot(site_scores[,3], site_scores[,4], col=c("#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FF7F00", "#CAB2D6"), pch=19, xlab= "PC-2", ylab = "PC-3", main="PC-3 vs PC-2")
legend("bottomleft", legend = unique(site_scores[,1]),col=c("#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FF7F00", "#CAB2D6"), pch=19, cex=0.5)

#PC4 vs PC1 figure
plot(site_scores[,2], site_scores[,5], col=c("#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FF7F00", "#CAB2D6"), pch=19, xlab= "PC-1", ylab = "PC-4", main="PC-4 vs PC-1")
legend("bottomleft", legend = unique(site_scores[,1]), col=c("#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FF7F00", "#CAB2D6"), pch=19, cex=0.5)

#PC4 vs PC2 figure
plot(site_scores[,3], site_scores[,5], col=c("#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FF7F00", "#CAB2D6"), pch=19, xlab= "PC-2", ylab = "PC-4", main="PC-4 vs PC-2 for Pathogen Data, grouped by site in river")
legend("bottomleft", legend = unique(site_scores[,1]), col=c("#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FF7F00", "#CAB2D6"), pch=19, cex=1)

#PC1 data
path_pca$scores[,1]
path_pc1scores <- as.data.frame(path_pca$scores[,1])

bodypath1 <- cbind(bodypath1, path_pc1scores) #adding PC1 scores as a column of bodypath1
library(dplyr)
names(bodypath1)[names(bodypath1)== "path_pca$scores[, 1]"] <- "PC1_scores"

write.csv(bodypath1, "wdata/bodypathogenanalysis_data2019.csv")

# Hypothesis #1 ===  Body size, fecundity, and energy density of sockeye are negatively correlated to pathogen prevalence.

# response variables = size corrected body mass, energy density, total energy
# explanatory variables = pathogen richness, pathogen PC scores

# lm(Y ~ X)

#pathogen richness as explanatory
pathr_scbm_lm <- lm(bodypath1$sc_bodymass ~ bodypath1$path_richness)
summary(pathr_scbm_lm)
anova(pathr_scbm_lm)
ggplot(bodypath1, aes(bodypath1$path_richness, bodypath1$sc_bodymass)) + geom_point() + geom_smooth(method = "lm", col = "blue", ) + xlab("Pathogen Richness") + ylab("Size Corrected Body Mass")

pathr_ED_lm <- lm(bodypath1$EnergyDensity_mJ.kg_1 ~ bodypath1$path_richness)
summary(pathr_ED_lm)
anova(pathr_ED_lm)
ggplot(bodypath1, aes(bodypath1$path_richness, bodypath1$EnergyDensity_mJ.kg_1)) + geom_point() + geom_smooth(method = "lm", col = "blue") + xlab("Pathogen Richness") + ylab("Energy Density (mJ/kg")

pathr_TE_lm <- lm(bodypath1$totalE ~ bodypath1$path_richness)
anova(pathr_TE_lm)
summary(pathr_TE_lm)
ggplot(bodypath1, aes(bodypath1$path_richness, bodypath1$totalE)) + geom_point() + geom_smooth(method = "lm", col = "blue") + xlab("Pathogen Richness") + ylab("Total Energy (mJ)")


#pathogen PC Scores as explanatory
pathscore_scbm_lm <- lm(bodypath1$sc_bodymass ~ bodypath1$PC1_scores)
anova(pathscore_scbm_lm)
summary(pathscore_scbm_lm)
ggplot(bodypath1, aes(bodypath1$PC1_scores, bodypath1$sc_bodymass)) + geom_point() + geom_smooth(method = "lm", col = "blue") + xlab("Pathogen PC1 Score") + ylab("Size Corrected Body Mass")


pathscore_ED_lm <- lm(bodypath1$EnergyDensity_mJ.kg_1 ~ bodypath1$PC1_scores)
anova(pathscore_ED_lm)
summary(pathscore_ED_lm)
ggplot(bodypath1, aes(bodypath1$PC1_scores, bodypath1$EnergyDensity_mJ.kg_1)) + geom_point() + geom_smooth(method = "lm", col = "blue") + xlab("Pathogen PC1 Score") + ylab("Energy Density")


pathscore_TE_lm <- lm(bodypath1$totalE ~ bodypath1$PC1_scores)
anova(pathscore_TE_lm)
summary(pathscore_TE_lm)
ggplot(bodypath1, aes(bodypath1$PC1_scores, bodypath1$totalE)) + geom_point() + geom_smooth(method = "lm", col = "blue") + xlab("Pathogen PC1 Score") + ylab("Total Energy")



#Richness Plots for Data Presentation
install.packages("gridExtra")
library(gridExtra)
richness_scbm_plot <- ggplot(bodypath1, aes(path_richness, sc_bodymass)) + geom_point() + geom_smooth(method = "lm", col = "blue", ) + xlab("Pathogen Richness") + ylab("Residuals for Size Corrected Body Mass") + theme(axis.text=element_text(size=24), axis.title=element_text(size=24, face="bold"))

richness_ED_plot <- ggplot(bodypath1, aes(path_richness, EnergyDensity_mJ.kg_1)) + geom_point() + geom_smooth(method = "lm", col = "blue") + xlab("Pathogen Richness") + ylab("Energy Density (mJ/kg)") + theme(axis.text=element_text(size=24), axis.title=element_text(size=24, face="bold"))

richness_TE_plot <- ggplot(bodypath1, aes(path_richness, totalE)) + geom_point() + ylim(20,80) + geom_smooth(method = "lm", col = "blue") + xlab("Pathogen Richness") + ylab("Total Energy (mJ)") + theme(axis.text=element_text(size=24), axis.title=element_text(size=24, face="bold"))

grid.arrange(richness_scbm_plot, richness_ED_plot, richness_TE_plot, ncol = 3)


#Load Plots for Data Presentation
loads_scbm_plot <- ggplot(bodypath1, aes(PC1_scores, sc_bodymass)) + geom_point() + xlim(-3.5,7.5) + geom_smooth(method = "lm", col = "blue") + xlab("Pathogen PC1 Score") + ylab("Residuals for Size Corrected Body Mass") + theme(axis.text=element_text(size=24), axis.title=element_text(size=24, face="bold"))

loads_ED_plot <- ggplot(bodypath1, aes(PC1_scores, EnergyDensity_mJ.kg_1)) + geom_point() + xlim(-3.5,7.5) + geom_smooth(method = "lm", col = "blue") + xlab("Pathogen PC1 Score") + ylab("Energy Density (mJ/kg)") + theme(axis.text=element_text(size=24), axis.title=element_text(size=24, face="bold"))

loads_TE_plot <- ggplot(bodypath1, aes(PC1_scores, totalE)) + geom_point() + xlim(-3.5,7.5) + ylim(20,80) + geom_smooth(method = "lm", col = "blue") + xlab("Pathogen PC1 Score") + ylab("Total Energy (mJ)") + theme(axis.text=element_text(size=24), axis.title=element_text(size=24, face="bold"))

grid.arrange(loads_scbm_plot, loads_ED_plot, loads_TE_plot, ncol = 3)




# Hypothesis #2 ===  Sockeye in early run-timing groups will have lower pathogen richness & loads than sockeye in later run-timing groups.

# response variables = pathogen richness, pathogen PC scores
# explanatory variables = site (b/c only "early run timing" fish taken for pathogens in CC)

# lm(Y ~ X)

bodypath1$site <- factor(bodypath1$site,
                             levels = c("CC",
                                        "MN",
                                        "TN",
                                        "GH",
                                        "SA",
                                        "MA",
                                        "LL"),
                             labels = c("CC",
                                        "MN",
                                        "TN",
                                        "GH",
                                        "SA",
                                        "MA",
                                        "LL"))

#Response Variable =  pathogen richness
pathr_site_lm <- lm(bodypath1$path_richness ~ bodypath1$site)
anova(pathr_site_lm)
pathr_site_lm
ggplot(bodypath1, aes(site, path_richness, fill = site)) + geom_boxplot() + xlab("Site") + ylab("Pathogen Richness") + scale_fill_manual(values = c("#1F78B4", "#FB9A99","#CAB2D6", "#33A02C","#FF7F00", "#E31A1C","#B2DF8A")) + geom_jitter()+ theme(axis.text=element_text(size=24), axis.title=element_text(size=24, face="bold"), title = element_text(size=24, face="bold"), legend.text = element_text(size=24))


#response variable = pathogen load (PC score)
pathscore_site_lm <- lm(bodypath1$PC1_scores ~ bodypath1$site)
anova(pathscore_site_lm)
ggplot(bodypath1, aes(bodypath1$site, bodypath1$PC1_scores, fill = site)) + geom_boxplot() + xlab("Site") + ylab("Pathogen PC1 Score") + scale_fill_manual(values = c("#1F78B4", "#FB9A99","#CAB2D6", "#33A02C","#FF7F00", "#E31A1C","#B2DF8A")) + geom_jitter()+ theme(axis.text=element_text(size=24), axis.title=element_text(size=24, face="bold"), title = element_text(size=24, face="bold"), legend.text = element_text(size=24))


#Plots for Data Presentation
richness_site_plot <- ggplot(bodypath1, aes(site, path_richness, fill = site)) + geom_boxplot() + xlab("Site") + ylab("Pathogen Richness") + scale_fill_manual(values = c("#1F78B4", "#FB9A99","#CAB2D6", "#33A02C","#FF7F00", "#E31A1C","#B2DF8A")) + geom_jitter()+ theme(axis.text=element_text(size=24), axis.title=element_text(size=24, face="bold"), title = element_text(size=24, face="bold"), legend.text = element_text(size=24))

loads_site_plot <- ggplot(bodypath1, aes(bodypath1$site, bodypath1$PC1_scores, fill = site)) + geom_boxplot() + xlab("Site") + ylab("Pathogen PC1 Score") + scale_fill_manual(values = c("#1F78B4", "#FB9A99","#CAB2D6", "#33A02C","#FF7F00", "#E31A1C","#B2DF8A")) + ylim(-3,7.5)+ geom_jitter()+ theme(axis.text=element_text(size=24), axis.title=element_text(size=24, face="bold"), title = element_text(size=24, face="bold"), legend.text = element_text(size=24))

grid.arrange(richness_site_plot, loads_site_plot, ncol = 2)

```
```