---
title: "AH_AICc_energydensity~SP"
author: "Abby Host"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = TRUE)
```

### Loading Data
```{r include = FALSE}
rm(list = ls())
library(AICcmodavg)
library(lubridate)
library(ggplot2)

#data loading
bc19 <- read.csv("bodycomp_2019.csv")
bc20 <- read.csv("bodycomp_2020.csv")
bc21 <- read.csv("bodycomp_2021.csv")
#need to bind all together for total body comp dataset, Upper River river only

bc_UR_total <- rbind(bc19[61:172,], bc20[61:120,], bc21[61:180,])
write.csv(bc_UR_total, "upperriver_bodycomp_all.csv")
upperriver_bodycomp_all<-read.csv("upperriver_bodycomp_all.csv")[,-1]
#all data is loaded now

#need to add year to dataset
str(upperriver_bodycomp_all)
upperriver_bodycomp_all$Collection_Date <- as.Date(upperriver_bodycomp_all$Collection_Date)

# Create a new column 'year' from the collection_date
upperriver_bodycomp_all$Year <- year(upperriver_bodycomp_all$Collection_Date)
str(upperriver_bodycomp_all)

#replace blank cell in Sex with NA 
upperriver_bodycomp_all$Sex[upperriver_bodycomp_all$Sex == ""] <- NA
str(upperriver_bodycomp_all)

write.csv(upperriver_bodycomp_all, "upperriver_bodycomp_all.csv")
```

### Import Data for models, check for NAs and eliminate as needed

```{r, include = FALSE}
rm(list = ls())
upperriver_bodycomp_all <- "upperriver_bodycomp_all.csv"
DataSet <-read.csv("upperriver_bodycomp_all.csv")[,-1]


##### For the Upper River Data, I want to elimiate Power Creek Cordova, Eyak Weir Cordova, and Bone Creek data points as they don't apply to my spawning populations of interest ####
library(dplyr)

# use filter() to exclude the specific collection locations
DataSet <- DataSet %>%
  filter(!Collection_Location %in% c("Power Creek Cordova", "Eyak Weir Cordova", "Bone Creek"))


### Now, need to remove NAs that will mess up levels / model weight
any(is.na(DataSet$Collection_Location))
any(is.na(DataSet$Collection_Region))
any(is.na(DataSet$Year))
any(is.na(DataSet$Sex))
DataSet[is.na(DataSet$Sex), ] #row 88 and 111 has no sex value, eliminate it for models
DataSet <- DataSet[-c(88,111),] #excludes row missing sex file
any(is.na(DataSet$Sex)) #Now any NAs that cannot be estimated have been removed for the explanatory variables

#Response variable, check for NAs
any(is.na(DataSet$EnergyPDry_1))
DataSet[is.na(DataSet$EnergyPDry_1), ] #Row 36 does not have a Energy Content 1 value, so eliminate for analysis
DataSet <- DataSet[-c(36),]
any(is.na(DataSet$EnergyPDry_1)) # False


# View DataSet.
head(DataSet)
summary(DataSet)
nrow(DataSet)
str(DataSet)

#make response variables factors
DataSet$Collection_Location <- as.factor(DataSet$Collection_Location)
levels(DataSet$Collection_Location) # 10 unique locations
DataSet$Year<- as.factor(DataSet$Year)
DataSet$Sex<- as.factor(DataSet$Sex)
DataSet$Collection_Region <- as.factor(DataSet$Collection_Region)
levels(DataSet$Collection_Region) # 4 Levels
DataSet$SpawnStatus <- as.factor(DataSet$SpawnStatus) #should be 4 levels
str(DataSet)

```


### Making Models for EnergyPDry_1\~SpawningPopulation, includes SpawnStatus
```{r}
# Models for reference
energypdry_SP_modelset <- "energydensity_spawningpopulation/EnergyPDry_1~SpawningPopulation_modelset.csv"

ModelSet<-read.csv(energypdry_SP_modelset)

Emodel1 <- lm(EnergyPDry_1~1, data=DataSet)
Emodel2 <- lm(EnergyPDry_1~ SpawnStatus + Collection_Location, data = DataSet)
Emodel3 <- lm(EnergyPDry_1~ SpawnStatus + Sex, data = DataSet)
Emodel4 <- lm(EnergyPDry_1~SpawnStatus + Year, data = DataSet)
Emodel5 <- lm(EnergyPDry_1~ SpawnStatus + Collection_Region, data = DataSet)
summary(Emodel5)
Emodel6 <- lm(EnergyPDry_1~ SpawnStatus + Collection_Location + Sex, data = DataSet)
Emodel7 <- lm(EnergyPDry_1~ SpawnStatus + Collection_Region + Sex, data = DataSet)
Emodel8 <- lm(EnergyPDry_1~ SpawnStatus + Collection_Location + Year, data = DataSet)
Emodel9 <- lm(EnergyPDry_1~SpawnStatus + Collection_Region + Year, data = DataSet)
Emodel10 <- lm(EnergyPDry_1~ SpawnStatus + Sex + Year, data = DataSet)
Emodel11 <- lm(EnergyPDry_1~ SpawnStatus + Collection_Region + Sex + Collection_Region:Sex, data = DataSet)
Emodel12 <- lm(EnergyPDry_1~ SpawnStatus + Collection_Region + Year + Collection_Region:Year, data = DataSet)
Emodel13 <- lm(EnergyPDry_1~SpawnStatus + Sex + Year + Sex:Year, data = DataSet)
Emodel14 <- lm(EnergyPDry_1~ SpawnStatus + Collection_Location + Collection_Region + Sex + Year, data = DataSet)
summary(Emodel14)
```

### AICc Model Selection

```{r}
AIC(Emodel1, Emodel2, Emodel3, Emodel4, Emodel5, Emodel6, Emodel7, Emodel8, Emodel9, Emodel10, Emodel11, Emodel12, Emodel13, Emodel14)

edModels <- list(Emodel1, Emodel2, Emodel3, Emodel4, Emodel5, Emodel6, Emodel7, Emodel8, Emodel9, Emodel10, Emodel11, Emodel12, Emodel13, Emodel14)

# Generate AIC table
mynames_ed <- paste("model", as.character(1:14), sep = "")
ed_aicc <- aictab(edModels, modnames = mynames_ed)
print(ed_aicc) #so model 14 is preferred 

# Convert AIC table to a data frame for easier manipulation
EDaic_df <- as.data.frame(ed_aicc)
EDaic_df$ModelName <- c("EnergyPDry_1~ SpawnStatus + Collection_Location + Collection_Region + Sex + Year",
                        "EnergyPDry_1~ SpawnStatus + Collection_Location + Sex",
                        "EnergyPDry_1~ SpawnStatus + Collection_Location + Year",
                        "EnergyPDry_1~ SpawnStatus + Collection_Region + Year + Collection_Region:Year",
                        "EnergyPDry_1~ SpawnStatus + Collection_Location",
                        "EnergyPDry_1~ SpawnStatus + Collection_Region + Sex + Collection_Region:Sex",
                        "EnergyPDry_1~SpawnStatus + Collection_Region + Year",
                        "EnergyPDry_1~ SpawnStatus + Collection_Region + Sex",
                        "EnergyPDry_1~ SpawnStatus + Collection_Region",
                        "EnergyPDry_1~ SpawnStatus + Sex + Year",
                        "EnergyPDry_1~SpawnStatus + Sex + Year + Sex:Year",
                        "EnergyPDry_1~ SpawnStatus + Sex",
                        "EnergyPDry_1~SpawnStatus + Year",
                        "EnergyPDry_1~1")
colnames(EDaic_df)[colnames(EDaic_df) == "Modnames"] <- "Model #"

write.csv(EDaic_df, file = "energydensity_spawningpopulation/AICresults_EnergyPDry_1~SpawningPopulation.csv", row.names = FALSE)

```

### Model Averaging

```{r}
library(MuMIn)

 # Create a model selection table (this will give you AIC, AIC weights, etc.)
model_weights <- ed_aicc$AICcWt ##Get the AIC weights from the AIC table
model_avg <- model.avg(edModels, weights = model_weights)
summary(model_avg)
avg_coefs <- coef(model_avg)

avg_confint <- confint(model_avg)
avg_se <- sqrt(diag(vcov(model_avg)))

# Convert the coefficients into a tidy data frame
coefs_df <- as.data.frame(avg_coefs)
colnames(coefs_df) <- "Avg_Coef"
coefs_df$CI_Lower <- avg_confint[, 1]  # Add lower bound of confidence intervals
coefs_df$CI_Upper <- avg_confint[, 2] # Add upper bound of confidence intervals
coefs_df$SE <- avg_se
print(coefs_df) #Model Averaging Coefficients for AIC model selection approach with body size as response variable

write.csv(coefs_df, file = "energydensity_spawningpopulation/EnergyPDry_1~spawningpopulation_models_CoefEstimates.csv", row.names = TRUE)
```

### Figure that displays parameter estimates + CI for each parameter in the model set

```{r}
paramestimates_energypdry <- "energydensity_spawningpopulation/EnergyPDry_1~spawningpopulation_models_CoefEstimates.csv"

paramestimates_energy<-read.csv(paramestimates_energypdry)
str(paramestimates_energy)

levels(factor(paramestimates_energy$X))
paramestimates_energy$X <- factor(paramestimates_energy$X, 
                           levels = rev(factor(paramestimates_energy$X)))


library(ggplot2)
ggplot(paramestimates_energy, aes(x = Avg_Coef, y = X)) + 
  geom_point(size = 3) +  # For the coefficient estimate as dots
  geom_errorbarh(aes(xmin = CI_Lower, xmax = CI_Upper), height = 0.2) + # Horizontal CI bars
  labs(x = "Parameter Estimate", y = "Parameter") +
  geom_vline(xintercept = 0, color = "red", linetype = "dashed", size = 1) +
  theme_minimal() 
  # + theme(axis.title = element_text(size = 24), 
       # axis.text = element_text(size = 24))

library(dplyr)
paramestimates_energy_filtered <- paramestimates_energy %>%
  filter(!X %in% c("SpawnStatus0", "SpawnStatus1", "SpawnStatus2", "SpawnStatus3"))  # Filter out specific levels

ggplot(paramestimates_energy_filtered, aes(x = Avg_Coef, y = X)) + 
  geom_point(size = 3) +  # For the coefficient estimate as dots
  geom_errorbarh(aes(xmin = CI_Lower, xmax = CI_Upper), height = 0.2) + # Horizontal CI bars
  labs(x = "Parameter Estimate", y = "Parameter") +
  geom_vline(xintercept = 0, color = "red", linetype = "dashed", size = 1) +
  theme_minimal()
  # + theme(axis.title = element_text(size = 24), 
       # axis.text = element_text(size = 24))

# SAVE HERE: ggsave("energydensity_spawningpopulation/Energy_ParamEstimates_Plot.png", plot=energy_plot, height=12, width=12, units="in")
```

### Figures for Copper River Workshop February 2025
```{r, echo=TRUE, results='hide', warning=FALSE, message=FALSE}
# Pete wants a figure/visualization of energy content of various spawning populations

### Import Data for models, check for NAs and eliminate as needed
rm(list = ls())
upperriver_bodycomp_all <- "upperriver_bodycomp_all.csv"
DataSet <-read.csv("upperriver_bodycomp_all.csv")[,-1]

##### For the Upper River Data, I want to eliminate Power Creek Cordova, Eyak Weir Cordova, Copper Lake, Upper Klutina, and Bone Creek data points as they don't apply to my spawning populations of interest ####
library(dplyr)

# use filter() to exclude the specific collection locations
DataSet <- DataSet %>%
  filter(!Collection_Location %in% c("Power Creek Cordova", "Eyak Weir Cordova", "Bone Creek", "Upper Klutina", "Copper Lake"))


### Now, need to remove NAs that will mess up levels / model weight
any(is.na(DataSet$Collection_Location))
any(is.na(DataSet$Collection_Region))
any(is.na(DataSet$Year))
any(is.na(DataSet$Sex))
DataSet[is.na(DataSet$Sex), ] #row 88 and 111 has no sex value, eliminate it for models
DataSet <- DataSet[-c(88,111),] #excludes row missing sex file
any(is.na(DataSet$Sex)) #Now any NAs that cannot be estimated have been removed for the explanatory variables

#Response variable, check for NAs
any(is.na(DataSet$EnergyPDry_1))
DataSet[is.na(DataSet$EnergyPDry_1), ] #Row 36 does not have a Energy Content 1 value, so eliminate for analysis
DataSet <- DataSet[-c(36),]
any(is.na(DataSet$EnergyPDry_1)) # False


# View DataSet.
head(DataSet)
summary(DataSet)
nrow(DataSet)
str(DataSet)

#make response variables factors
DataSet$Collection_Location <- as.factor(DataSet$Collection_Location)
levels(DataSet$Collection_Location) # 10 unique locations
DataSet$Year<- as.factor(DataSet$Year)
DataSet$Sex<- as.factor(DataSet$Sex)
DataSet$Collection_Region <- as.factor(DataSet$Collection_Region)
levels(DataSet$Collection_Region) # 4 Levels
DataSet$SpawnStatus <- as.factor(DataSet$SpawnStatus) #should be 4 levels
DataSet2 <- DataSet %>%
  filter(Strontium_marked_Y.N != "NO READ")
DataSet2$Strontium_marked_Y.N <- as.factor(DataSet2$Strontium_marked_Y.N)
levels(DataSet2$Strontium_marked_Y.N) #Now only Y and N available


                #### Strontium Analysis of Energy ######
str(DataSet2)
#first I want to determine which collection_location levels contain fish samples with both Y and N strontium markings for comparison of energyPdry_1
locations_with_both <- DataSet2 %>%
  group_by(Collection_Location) %>%
  filter(any(Strontium_marked_Y.N == "Y") & any(Strontium_marked_Y.N == "N")) %>%
  pull(Collection_Location) %>%
  unique()

# Filter dataset to keep only the locations with both "Y" and "N" levels
strontium_data <- DataSet2 %>%
  filter(Collection_Location %in% locations_with_both)

#So all of this Y fish are in Gulkana or Fish creek with an exception of one return fish that was collected at Mentasta-- important to note! but for the sake of visualization, I am removing that fish
strontium_data <- strontium_data %>%
  filter(Collection_Location != "Mentasta")


library(ggplot2)
#Now, I want to further visualize this by year (2019, 2020, 2021)
# Boxplot comparing EnergyPDry_1 by Strontium Y/N and Year
ggplot(strontium_data, aes(x = Strontium_marked_Y.N, y = EnergyPDry_1, fill = Strontium_marked_Y.N)) +
  geom_boxplot() +
  facet_grid(~ Year) + 
  labs(title = "The energy content (mJ/kg) of strontium marked and non-marked sockeye from Gulkana Hatchery and Fish Creek \nduring the 2019-2021 sampling seasons.",
       x = "Strontium Level (Y/N)",
       y = "Energy (EnergyPDry_1)",
       fill = "Presence of \nStrontium Mark") + 
  theme_classic() +
  scale_x_discrete(labels = c("Y" = "Marked", "N" = "Non-Marked")) + 
  scale_fill_manual(values = c("Y" = "red", "N" = "blue"),
                    labels = c("Y" = "Marked", "N" = "Non-Marked"))  # Change legend labels

  # + theme(
  #  plot.title = element_text(size = 40, face = "bold"),  # Title size
  #  axis.title.x = element_text(size = 20),  # X-axis title size
  #  axis.title.y = element_text(size = 20),  # Y-axis title size
  #  axis.text.x = element_text(size = 30, angle = 45, hjust = 1),   # X-axis tick labels size
  #  axis.text.y = element_text(size = 30),   # Y-axis tick labels size
  #  legend.title = element_text(size = 40),  # Legend title size
  #  legend.text = element_text(size = 30), # Legend labels size
  #  strip.text = element_text(size = 40, face = "bold")) 


  





                ##### Energy Analysis of Pre-Spawn Fish #####

# use filter() to exclude the any partial/post/anomolous spawned fish
DataSet_prespawn <- DataSet %>%
  filter(!SpawnStatus %in% c("1","2","3"))

# use filter() to exclude the any partial/anomolous spawned fish
DataSet_prepostspawn <- DataSet %>%
  filter(!SpawnStatus %in% c("1","3"))



# Relevel the factor in one step
DataSet_prespawn$Collection_Location <- factor(DataSet_prespawn$Collection_Location,
                             levels = c("Long Lake", 
                                      "Klutina River", 
                                      "Mahlo", 
                                      "St Anne",
                                      "Mentasta", 
                                      "Tanada", 
                                      "Gulkana Hatchery", 
                                      "Fish Creek Gulkana"))

  # Faceted boxplot by Year and Collection Location
ggplot(DataSet_prespawn, aes(x = Collection_Location, y = EnergyPDry_1)) +
  geom_boxplot(aes(fill = Collection_Location), alpha = 0.6) +
  facet_wrap(~ Year) +
  labs(title = "Differences of energy content (mJ/kg) of pre-spawn sockeye sampled from different \nspawning locations in the Copper River Basin, separated by sampling year (2019-2021)",
       x = "Collection Location",
       y = "Energy Content (mJ/kg)") + 
   guides(fill = "none") + 
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1))
  #  plot.title = element_text(size = 40, face = "bold"),  # Title size
  #  axis.title.x = element_text(size = 30, face = "bold"),  # X-axis title size
  #  axis.title.y = element_text(size = 30, face = "bold"),  # Y-axis title size
  #  axis.text.x = element_text(size = 30, angle = 60, hjust = 1),   # X-axis tick labels size
  #  axis.text.y = element_text(size = 30),
  #  strip.text = element_text(size = 40, face = "bold")) 

# TO SAVE: ggsave("energydensity_spawningpopulation/CopperRiverWS_EnergyYearSP_prespawn.jpeg", plot=g2, height=16, width=26, units="in")


# Line plot of mean Energy Density by Collection Location and Year
data_summary <- DataSet_prespawn %>%
  group_by(Year, Collection_Location) %>%
  summarise("Energy Content" = mean(EnergyPDry_1, na.rm = TRUE))

ggplot(data_summary, aes(x = Year, y = `Energy Content`, group = Collection_Location, color = Collection_Location)) +
  geom_line(size = 2) +
  geom_point(size = 4) +
  labs(title = "Trends of mean energy content (mJ/kg) of pre-spawn sockeye across sampling year (2019-2021) and collection location",
       x = "Year",
       y = "Mean Energy Content (mJ/kg)")



### Pre vs Post Spawn energy differences in sockeye for 2019-2021 only
# Ensure 'Year' is a factor variable (if not already)
DataSet_prepostspawn$Year <- as.factor(DataSet_prepostspawn$Year)

#Per Pete's request, filter data so that it includes collection_locations only that contain pre AND post data points:
library(dplyr)

location_summary <- DataSet %>%
  filter(SpawnStatus %in% c(0, 2)) %>%  # Keep only 0 and 2
  group_by(Collection_Location) %>%
  summarise(has_pre_spawn = any(SpawnStatus == 0), 
            has_post_spawn = any(SpawnStatus == 2)) %>%
  filter(has_pre_spawn & has_post_spawn)  # Keep only locations with both 0 and 2

# View the table
print(location_summary)

DataSet_prepostspawnLoc <- DataSet %>%
  filter(!SpawnStatus %in% c("1", "3")) %>%  # Exclude SpawnStatus 1 and 3
  group_by(Collection_Location) %>%
  filter(all(c(0, 2) %in% SpawnStatus)) %>%
  ungroup()  # Remove grouping after filtering


ggplot(DataSet_prepostspawnLoc, aes(x = SpawnStatus, y = EnergyPDry_1, fill = SpawnStatus)) +
  geom_boxplot(alpha = 0.6) + # Color for pre-spawn and post-spawn
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Differences of energy content (mJ/kg) between pre-spawn and \npost-spawn sockeye sampled in the Copper River Basin from 2019-2021",
       x = "Spawn Status",
       y = "Energy Content (mJ/kg)",
       fill = "SpawnStatus") +
  facet_wrap(~ Collection_Location) +
  theme_classic() +   
  scale_fill_manual(values = c("0" = "skyblue", "2" = "salmon"),
                    labels = c("0" = "Pre-Spawn", "2" = "Post-Spawn")) + 
  scale_x_discrete(labels = c("0" = "Pre-Spawn", "2" = "Post-Spawn"))
    #+ theme( 
    # plot.title = element_text(size = 40, face = "bold"),  # Title size
    # axis.title.x = element_text(size = 30, face = "bold"),  # X-axis title size
    #axis.title.y = element_text(size = 30, face = "bold"),  # Y-axis title size
    #axis.text.x = element_text(size = 30),   # X-axis tick labels size
    #axis.text.y = element_text(size = 30),
    #strip.text = element_text(size = 40),
    #legend.title = element_text(size = 40, face = "bold"),
    #legend.text = element_text(size = 30)) 



### Include partial spawn data for long lake
str(DataSet)
library(dplyr)

DataSet_prepartialspawnLoc <- DataSet %>%
  filter(!SpawnStatus %in% c("2", "3")) %>%  # Exclude SpawnStatus 2 and 3
  group_by(Collection_Location) %>%
  filter(all(c(0, 1) %in% SpawnStatus)) %>%
  ungroup()  # Remove grouping after filtering


gpartial <- ggplot(DataSet_prepartialspawnLoc, aes(x = SpawnStatus, y = EnergyPDry_1, fill = SpawnStatus)) +
  geom_boxplot(alpha = 0.6) + # Color for pre-spawn and post-spawn
  labs(title = "Differences of energy content (mJ/kg) between pre-spawn and \npartial-spawn sockeye sampled in the Copper River Basin from 2019-2021",
       x = "Spawn Status",
       y = "Energy Content (mJ/kg)",
       fill = "SpawnStatus") +
  facet_wrap(~ Collection_Location) +
  theme_classic() +   
  scale_fill_manual(values = c("0" = "skyblue", "1" = "purple"),
                    labels = c("0" = "Pre-Spawn", "1" = "Partial-Spawn")) + 
  scale_x_discrete(labels = c("0" = "Pre-Spawn", "1" = "Partial-Spawn"))
 # + theme(
   # plot.title = element_text(size = 40, face = "bold"),  # Title size
   # axis.title.x = element_text(size = 30, face = "bold"),  # X-axis title size
   # axis.title.y = element_text(size = 30, face = "bold"),  # Y-axis title size
   # axis.text.x = element_text(size = 30, angle = 45, hjust = 1),   # X-axis tick labels size
   # axis.text.y = element_text(size = 30),
   # strip.text = element_text(size = 40),
   # legend.title = element_text(size = 40, face = "bold"),
   # legend.text = element_text(size = 30)) 

ggsave("energydensity_spawningpopulation/CopperRiverWS_EnergyPrePartialSpawnLoc.jpeg", plot=gpartial, height=16, width=20, units="in")

ggplot(DataSet_prepartialspawnLoc, aes(x = SpawnStatus, y = EnergyPDry_1, fill = SpawnStatus)) +
  geom_boxplot(alpha = 0.6) + # Color for pre-spawn and post-spawn
  labs(title = "Differences of energy content (mJ/kg) between pre-spawn and \npartial-spawn sockeye sampled in the Copper River Basin from 2019-2021",
       x = "Spawn Status",
       y = "Energy Content (mJ/kg)",
       fill = "SpawnStatus") +
  facet_wrap(~ Collection_Location) +
  theme_classic() +   
  scale_fill_manual(values = c("0" = "skyblue", "1" = "purple"),
                    labels = c("0" = "Pre-Spawn", "1" = "Partial-Spawn")) + 
  scale_x_discrete(labels = c("0" = "Pre-Spawn", "1" = "Partial-Spawn"))

```
