---
title: "AH_AICc_energydensity~GSI"
author: "Abby Host"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, eval = TRUE)
```

#' =====================================================
#' AICc code for EnergyPDry_1~GSI models
#' =====================================================


NOTE!!!! Need to ensure what level of assignment likelihood we are using for inclusion in GSI analysis!

### Loading Data
```{r}
rm(list = ls())
library(AICcmodavg)
library(lubridate)
library(ggplot2)

#data loading
gsi20 <- read.csv("GSI_lowerriver20.csv")[,-1]
gsi21 <- read.csv("GSI_lowerriver21.csv")
#need to bind all together for total body comp GSI dataset, lower river only

gsi_LR_total <- rbind(gsi20[1:60,], gsi21[1:60,])
write.csv(gsi_LR_total, "lowerriver_GSI_all.csv")
lowerriver_GSI_all<-read.csv("lowerriver_GSI_all.csv")[,-1]
#all data is loaded now
#Year already included as a variable/column

#replace blank cell in Sex with NA 
lowerriver_GSI_all$Sex[lowerriver_GSI_all$Sex == ""] <- NA
str(lowerriver_GSI_all)

write.csv(lowerriver_GSI_all, "lowerriver_GSI_all.csv")

```

### Import Data for models
```{r}
rm(list = ls())
lowerriver_GSI_all <- "lowerriver_GSI_all.csv"

# Import the data. Be sure to check the structure of the data and that R is reading continuous and categorical variables appropriately.
DataSet<-read.csv(lowerriver_GSI_all)[,-1] #83 variables, 120 observations b/c one row with NA sex is removed


### Removing NAs that will mess up levels / model weight
any(is.na(DataSet$Collection_Location))
any(is.na(DataSet$Group_Assignment))
any(is.na(DataSet$Year))
any(is.na(DataSet$Sex))
DataSet[is.na(DataSet$Sex), ] #row 115 has no sex value, eliminate it for models
DataSet <- DataSet[-55,] #excludes row missing sex file
any(is.na(DataSet$Sex)) 

# View DataSet.
head(DataSet)
summary(DataSet)
nrow(DataSet)
str(DataSet)

#make response variables factors
DataSet$Collection_Location <- as.factor(DataSet$Collection_Location)
DataSet$Group_Assignment <- as.factor(DataSet$Group_Assignment)
levels(DataSet$Group_Assignment) #levels are not all consistent. Need to fix this

# Strip whitespace
DataSet$Group_Assignment <- trimws(DataSet$Group_Assignment)

# Standardize levels
DataSet$Group_Assignment <- factor(DataSet$Group_Assignment)
levels(DataSet$Group_Assignment)


# Clean up levels manually
levels(DataSet$Group_Assignment)[levels(DataSet$Group_Assignment) == "Gulkana "] <- "Gulkana"
levels(DataSet$Group_Assignment)[levels(DataSet$Group_Assignment) == "Gulkanahatchery"] <- "GulkanaHatchery"
levels(DataSet$Group_Assignment)[levels(DataSet$Group_Assignment) == "KlutinaTonsinaOutlets"] <- "KlutinaTonsinaOutlet"
levels(DataSet$Group_Assignment)[levels(DataSet$Group_Assignment) == "insufficient genotypes"] <- "insufficient_genotypes"

# Then drop the insufficient genotypes
DataSet <- subset(DataSet, Group_Assignment != "insufficient_genotypes")
DataSet$Group_Assignment <- droplevels(DataSet$Group_Assignment)

# Confirm new levels
levels(DataSet$Group_Assignment)


DataSet$Year<- as.factor(DataSet$Year)
DataSet$Sex<- as.factor(DataSet$Sex)
str(DataSet) #collection_rivermile_m is numeric

```